### ISSUE TITLE
Calling twice LabeConnector shoudn't end in two overlaid connectors

### ISSUE THREAD

**Issue by haubourg** [Oslandia/labelconnector#10]
Current logic applies a new geometry generator each time. 
We could set tags into the geometry expression so that if a geometry generator is already there, with the tags, the plugin would only replace the expression 

It is also a possibility to explain user where the expression comes from :

![image](https://user-images.githubusercontent.com/1629853/58015402-6ddb9d80-7afb-11e9-8084-3ef2655c1f76.png)

**Comment by lbartoletti** [comment]
> Current logic applies a new geometry generator each time.

Is generated twice if the current style have already an expression for our plugins.

I had seen this in my tests, but I didn't worry about it, since I think it was my responsibility as a user to verify the behavior of the new style or to apply it from a style that didn't contain these arrows.

So, yes, we can verify if the style already has a geometry of the plugin, but what should we do next? 

Some questions I had asked myself:
Is it prevented? Does the user want to customize a second arrow according to a condition?
Is it definitely a bug? Isn't it the responsibility of the user to control it?


> It is also a possibility to explain user where the expression comes from :

Good Idea!

**Comment by lbartoletti** [comment]
> > It is also a possibility to explain user where the expression comes from :
> 
> Good Idea!

Done in https://github.com/Oslandia/labelconnector/commit/3ae3e2b0e2fee4744cf15187b7ebd56bc521efc3

**Comment by haubourg** [comment]
Nice, works smoothly
