### ISSUE TITLE
Remplacement des contenus d'étiquettes par l'identifiant après activation

### ISSUE THREAD

**Issue by FERRATON** [Oslandia/labelconnector#15]
Dès activation de Label connector et après désignation de la clef primaire à utiliser,  il remplace les étiquettes actuelles (par exemple NOM_COMM dans le fichier joint) par l'identifiant (dans l'exemple joint fid)
[COMMUNES.zip](https://github.com/Oslandia/labelconnector/files/3324647/COMMUNES.zip)

**Comment by haubourg** [comment]
@lbartoletti I think the issue lies here : https://github.com/Oslandia/labelconnector/blob/master/label_connector.py#L320 

We need to get the existing field name used for labeling if it is set and keep it. 
If none is set, we might raise a dialog to ask user to choose it (but it would be an enhancement)

**Comment by FERRATON** [comment]
Dans mon exemple j'active une étiquette (ici NOM_COMM) puis je lance labelconnector. Il y a donc bien une étiquette active (QGIS 3.4.5)
![exemple](https://user-images.githubusercontent.com/2129643/60095580-2cb85800-974f-11e9-9887-7790d20f23cc.png)

**Comment by haubourg** [comment]
@FERRATON merci pour la remontée. Je confirme le comportement chez moi. On regarde pour corriger ça.

**Comment by lbartoletti** [comment]
Merci.

C'est corrigé dans https://github.com/Oslandia/labelconnector/commit/c49d74b5910b359b081aeba91854b3fd5ccff3ce

Dans le cas d'une étiquette simple, je récupère le champs présent ou l'expression présente
